runtime: nodejs22
handlers:
# Serve all static files with url ending with a file extension
- url: /(.*\..+)$
  static_files: build/index.html
  upload: /(.*\..+)$
# Catch all handlers to index.html
- url: /.*
  static_files: build/index.html
  upload: build/index.html