apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirstpodrc
  labels:
    app: node
spec:
  template:
    metadata:
      name: myfirstpod
      labels:
        app: node
    spec:
      containers:
        - name: myfirstpod
          image: anodiamdn638/test-image:4.0
  replicas : 3